version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn SPDA_Project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/SPDA_Project/web/staticfiles
      - media_volume:/home/SPDA_Project/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=spda_user
      - POSTGRES_PASSWORD=h4fg0xznf_HCNrq*dsdsa21?d
      - POSTGRES_DB=spda_project





volumes:
  postgres_data:
  static_volume:
  media_volume: