version: '3.7'

services:
  web:
    build:
      context: ./SPDA_Project
      dockerfile: ./Dockerfile
    command: gunicorn SPDA_Project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/SPDA_Project/web/staticfiles
      - media_volume:/home/SPDA_Project/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./SPDA_Project/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=spda_user
      - POSTGRES_PASSWORD=h4fg0xznf_HCNrq*dsdsa21?d
      - POSTGRES_DB=spda_project
  frontend:
    build:
      context: ./SPDA_Project_front
    command: [ "npm", "start" ]
    volumes:
      - ./SPDA_Project_front:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - 3000:3000

volumes:
  postgres_data:
  static_volume:
  media_volume:
  node-modules: