# Generated by Django 3.1.3 on 2020-11-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=256, verbose_name='surname')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('course_name', models.CharField(max_length=256, verbose_name='course name')),
                ('link', models.CharField(max_length=512, verbose_name='link')),
                ('price', models.CharField(blank=True, max_length=256, verbose_name='price')),
                ('start_date', models.CharField(blank=True, max_length=256, verbose_name='start date')),
                ('study_quarter', models.IntegerField(default=1, verbose_name='study quarter')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
