# Generated by Django 3.1.3 on 2020-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='status',
            field=models.CharField(default='Ждёт одобрения', max_length=256, verbose_name='status'),
        ),
    ]
